#ifndef QUC_H
#define QUC_H

#include "gaugearc.h"
#include "gaugepercent.h"
#include "gaugecar.h"
#include "gaugecircle.h"
#include "gaugeclock.h"
#include "gaugecompass.h"
#include "gaugecompassx.h"
#include "gaugecompasspan.h"
#include "gaugedial.h"
#include "gaugemini.h"
#include "gaugeplane.h"
#include "gaugeprogress.h"
#include "gaugerange.h"
#include "gaugeround.h"
#include "gaugesimple.h"
#include "gaugewatch.h"
#include "gaugenet.h"
#include "gaugespeed.h"
#include "gaugelpm.h"
#include "gaugecolor.h"
#include "gaugecloud.h"
#include "gaugeweather.h"
#include "gaugedecibel.h"
#include "gaugepanel.h"
#include "gaugeedit.h"

#include "progressbutton.h"
#include "progresscolor.h"
#include "progresspercent.h"
#include "progressround.h"
#include "progresswait.h"
#include "progresswater.h"
#include "progressthree.h"
#include "progressplay.h"
#include "progressring.h"
#include "progressarc.h"
#include "progressshadow.h"
#include "progresstip.h"
#include "progresscountdown.h"

#include "battery.h"
#include "lightbutton.h"
#include "lightpoint.h"
#include "magicmouse.h"
#include "magicpenguin.h"
#include "magicfish.h"
#include "magicpool.h"
#include "roundcircle.h"
#include "roundwidget.h"
#include "roundlogo.h"
#include "roundtext.h"
#include "roundmenu.h"
#include "switchbutton.h"
#include "oventimer.h"
#include "tumbler.h"
#include "tumblerdatetime.h"
#include "lunarcalendaritem.h"
#include "lunarcalendarwidget.h"
#include "lunarcalendarinfo.h"
#include "tiledbg.h"
#include "telwidget.h"

#include "customgraphics.h"
#include "customrocker.h"
#include "custompie.h"
#include "customring.h"
#include "customdart.h"
#include "scantantan.h"
#include "spiderchart.h"
#include "shadowcalendar.h"
#include "shadowclock.h"
#include "shadowwidget.h"
#include "tasktableview.h"
#include "timeaxis.h"
#include "timeline.h"

#include "navbar.h"
#include "navbutton.h"
#include "navlabel.h"
#include "navlistview.h"
#include "navprogress.h"
#include "navbuttongroup.h"
#include "navtitle.h"
#include "navpage.h"

#include "wavebar.h"
#include "wavechart.h"
#include "wavedata.h"
#include "wavedouble.h"
#include "waveline.h"
#include "waveplot.h"
#include "wavewater.h"

#include "rulerbar.h"
#include "rulerline.h"
#include "rulerslider.h"
#include "rulerdouble.h"
#include "rulertemp.h"
#include "rulerscale.h"
#include "rulerprogress.h"

#include "sliderselect.h"
#include "sliderrange.h"
#include "slidertip.h"

#include "barvolume.h"
#include "barvumeter.h"

#include "colorcombobox.h"
#include "colorpanelbar.h"
#include "colorpanelfader.h"
#include "colorpanelhsb.h"
#include "colorpanelbtn.h"
#include "colorbutton.h"
#include "colorstyle.h"

#include "adswidget.h"
#include "adswidgetx.h"
#include "animationbutton1.h"
#include "animationbutton2.h"
#include "devicebutton.h"
#include "imageanimation.h"
#include "imagecalendar.h"
#include "imageclock.h"
#include "imagepilot.h"
#include "imagepower.h"
#include "imageswitch.h"
#include "imageview.h"

#include "antline.h"
#include "lcddatetime.h"
#include "lcdnumber.h"
#include "lednumber.h"
#include "ledtext.h"
#include "devicesizetable.h"
#include "cpumemorylabel.h"
#include "textmovewidget.h"
#include "panelitem.h"
#include "panelwidget.h"
#include "verifiedcode.h"
#include "iconeditor.h"
#include "ipaddress.h"
#include "selectwidget.h"
#include "flowlayout.h"
#include "squarelayout.h"

#include "videobox.h"
#include "videopanel.h"
#include "videoplayback.h"
#include "videowindow.h"

#include "flightadi.h"
#include "flightalt.h"
#include "flightasi.h"
#include "flighthsi.h"
#include "flightnav.h"
#include "flightpfd.h"
#include "flighttc.h"
#include "flightvsi.h"

#include "xlistwidget.h"
#include "xlistwidgetvs.h"
#include "xlistwidgetvt.h"
#include "xslider.h"
#include "xprogressbar.h"
#include "xcombobox.h"
#include "xstackwidget.h"
#include "xtablewidget.h"
#include "xmodelindex.h"
#include "xlineedit.h"

#include "ycontrol.h"
#include "ycombobox.h"
#include "yspinbox.h"
#include "ydoublespinbox.h"
#include "yscrollbarh.h"
#include "yscrollbarv.h"
#include "ylistwidget.h"
#include "ytreewidget.h"
#include "ytablewidget.h"

#include "bottomwidget.h"
#include "colorwidget.h"
#include "gifwidget.h"
#include "maskwidget.h"
#include "movewidget.h"
#include "screenwidget.h"

#include "framelesswidget2.h"
#include "framelessdialog.h"
#include "framelesswidget.h"
#include "framelessmainwindow.h"

#include "flatui.h"
#include "zhtopy.h"
#include "pinyin.h"
#include "ntpclient.h"
#include "savelog.h"
#include "saveruntime.h"
#include "trayicon.h"
#include "smoothcurve.h"
#include "base64helper.h"
#include "iconhelper.h"
#include "weather.h"
#include "cityhelper.h"

#endif // QUC_H
